version: "3.9"

services:
  zookeeper:
    image: bitnami/zookeeper:3.9
    container_name: ${KAFKA_ZOOKEEPER_NAME}
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - app-network
    ports:
      - "${ZOOKEEPER_PORT}:2181"

  broker:
    image: bitnami/kafka:3.7
    container_name: ${KAFKA_BROKER_NAME}
    networks:
      - app-network
    ports:
      - "${KAFKA_PORT}:9092"
      - "${KAFKA_EXTERNAL_PORT}:9093"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=${KAFKA_ZOOKEEPER_NAME}:2181
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://${KAFKA_BROKER_NAME}:9092,EXTERNAL://${KAFKA_EXTERNAL_HOST}:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - ${KAFKA_ZOOKEEPER_NAME}

networks:
  app-network:
    external: true